project:
  project-id: fl6801c3dd3148d231317d15
  project-name: wmio_project_b
  accounts:
    GoogleSheets_2209:
      secrets:
        - client_id
        - client_secret
        - access_token
        - refresh_token
        - token_type
        - refresh_token_expires_in
    GoogleSheet_1:
      secrets:
        - oauth_v20.refreshAccessToken
        - oauth_v20.accessTokenRefreshURL
        - oauth_v20.accessTokenRefreshURLRequest
        - oauth_v20.accessTokenRefreshCustomESBService
        - oauth.consumerId
