project:
  project-id: fl6801c3dd3148d231317d15
  project-name: wmio_project_b
  accounts:
    GoogleSheets_2209:
      secrets:
        - client_id
        - client_secret
        - access_token
        - refresh_token
